- name: configurating rabbitmq componet
  hosts: rabbitmq
  become: yes
  tasks:
  - name: installation of rabbitmq
    ansible.builtin.dnf:
       name: rabbitmq-server
       state: present
  
  - name: start and enable the rabbitmq service
    ansible.builtin.service:
       name: rabbitmq-server
       state: started
       enabled: yes

  - name: set rabbitmq password
    community.rabbitmq.rabbitmq_user:
      user: roboshop123
      password: roboshop
      permissions:
       - vhost: /
         configure_priv: .*
         read_priv: .*
         write_priv: .*
      state: present