- name: user compoent configuration
  hosts: user
  tasks:
  - name: default nodejs disable
    ansible.builtin.command: dnf module disable nodejs -y

  - name: nodejs20  enable
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: nodejs instalaltion
    ansible.builtin.dnf:
       name: nodejs
       state: present
  
  - name: system user id creation
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nlogin
      home: /app

  - name: directory creation
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: downloading the code
    ansible.builtin.get_url:
       url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip 
       dest: /tmp/user.zip

  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
       src: /tmp/user.zip
       dest: /app
       remote_src: yes
    
  - name: Install the dependencies
    community.general.npm:
        path: /app

  - name: copy the user service to systemd
    ansible:builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service
  
  - name: daemon-reload service
    ansible.builtin.systemd_service:
       daemon-reload: true
  
  - name: start and enable the user service
    ansible.builtin.service:
       name: user
       state: started
       enabled: yes